### ISSUE TITLE
Not respecting device width and height

### ISSUE THREAD

**Issue by thomassth** [hkbus/hk-independent-bus-eta#12] opened 2021-07-17 04:49 UTC
Tested on Firefox Focus on Android v8. 17.1(gecko 90) and Samsung internet 14.2.1.69 (chromium 87) .

In Firefox, only width is overflowing. In samsung internet, both width and height are overflowing

![Screenshot_20210717-124210_Samsung Internet.png](https://user-images.githubusercontent.com/8331853/126025841-a844aadd-ffcd-4ecd-8cd5-ff036255dd05.png)

**Comment by thomassth** [comment] 2021-07-24 13:39
Problem reappeared recently

Please reopen this issue

**Comment by chunlaw** [comment] 2021-07-24 13:43
Could you provide device information to reproduce the issue?

**Comment by thomassth** [comment] 2021-07-24 13:55
https://github.com/hkbus/hk-independent-bus-eta/commit/51a8244c7cfbaadd3ac65261d2ab9e6bbfb171c2

Removing "minWidth:0" probably is the problem

**Comment by chunlaw** [comment] 2021-07-24 14:06
🤔 Actually, I am not familiar with CSS. My full time work is mainly on data analysis. Would you mind to explain the importance of "minWidth: 0".

To me, setting "maxWidth: 20vh" seems to be more reasonable.

**Comment by thomassth** [comment] 2021-07-24 14:13
The root problem is the footer items are too wide, making the whole web page overflow.

maxwidth is not related in this issue.

minWidth: 0 is basically removing the min-width property, allowing browsers to shrink the footer items when needed.

**Comment by thomassth** [comment] 2021-07-24 14:15
You can actually test most if not all of these CSS changes with "inspect element" in all modern browsers.

I found it to be the best way to learn and understand CSS things.

**Comment by chunlaw** [comment] 2021-07-24 15:20
Great thanks, I found the inspector can emulate device width as well. Could you kindly state the device model you used that encounter the width issue?

**Comment by chunlaw** [comment] 2021-07-24 15:24
I have tried a narrow device, namely Moto G4, and cannot reproduce your issue.
![image](https://user-images.githubusercontent.com/4438690/126873129-fee596ce-4a27-47e1-95c4-87b3b2756ae6.png)

**Comment by chunlaw** [comment] 2021-07-24 15:29
#809028a
Fixed in the new commit
I have also added you as the contributor of the project. Cheers

**Closed by chunlaw** 2021-07-24 15:29 UTC
